// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcEBSuEyr2IqC9uuyaVK6oln861teunyY',
    appId: '1:846594942303:web:a89f01686d7630b3e8c2ea',
    messagingSenderId: '846594942303',
    projectId: 'appchat-ae6c8',
    authDomain: 'appchat-ae6c8.firebaseapp.com',
    storageBucket: 'appchat-ae6c8.appspot.com',
    measurementId: 'G-Y6LR8XDEVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzcTV0WLkt3DRUNcs29ntHo6QoWd5dG3A',
    appId: '1:846594942303:android:7615097af31a20ade8c2ea',
    messagingSenderId: '846594942303',
    projectId: 'appchat-ae6c8',
    storageBucket: 'appchat-ae6c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtUgLJXYvE-uXVtALrWjwLzr10AiaKss8',
    appId: '1:846594942303:ios:29f50413159dd011e8c2ea',
    messagingSenderId: '846594942303',
    projectId: 'appchat-ae6c8',
    storageBucket: 'appchat-ae6c8.appspot.com',
    iosBundleId: 'com.example.flutterChat',
  );
}
